2 oauth
ncedu-tlt/social-network pull request #12
Opened 2018-03-04 20:16 UTC by Tadoma

OAuth implemented

2018-03-05 08:02 UTC, ocassio requested changes

2018-03-05 08:02 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/config/SecurityConfig.java
> +    OAuth2ClientContext oauth2ClientContext;
1. Autowired лучше использовать через конструктор.
2. Никогда не оставляй поля без модификатора доступа.

2018-03-05 08:02 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/config/SecurityConfig.java
> +        OAuth2RestTemplate githubTemplate = new OAuth2RestTemplate(github(), oauth2ClientContext);
У тебя есть метод, который возвращает аналогичный RestTemplate. Почему просто не вызвать его?

2018-03-05 08:02 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/config/SecurityConfig.java
> +        return new OAuth2RestTemplate(github(), oauth2ClientContext);
Всегда в качестве возвращаемого типа используй наиболее абстрактный вариант. В данном случае RestTemplate.

2018-03-05 08:02 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/controllers/UserApiController.java
> +    private OAuth2RestTemplate restTemplate;
Аналогично, нужно использовать интерфейс RestClient. Если все будут использовать конкретную реализацию, будет очень сложно подменять логику.

2018-03-05 08:02 UTC, ocassio commented on src/main/vue/src/api/rest/user.api.js
> +        .then(window.location.href = '/');
Ты же в курсе, что в качестве функции обработчика ты передал значение window.location.href, а не функцию, которая его проставит. Более того, в в данной функции должен только совершаться колл. Что делать дальше, должен решать сам компонент, который его вызывает. И переход необходимо совершать с использовать vue-router, иначе мы лишний раз перезагрузим страницу.

2018-03-05 08:02 UTC, ocassio commented on src/main/vue/src/components/Auth.vue
> +        <v-btn v-else flat href="login/github">{{ $t('auth.login') }}</v-btn>
Всегда ссылки с "/". Иначе можно нарваться на неприятные сюрпризы.

2018-03-05 08:02 UTC, ocassio commented on src/main/vue/src/components/Auth.vue
> +import * as api from '@/api/rest/user.api';
Импортируй конкретную функцию, которой хочешь воспользоваться. Текущий подход убьет оптимизацию, которую выполняет webpack.

2018-03-05 08:02 UTC, ocassio commented on src/main/vue/src/components/Auth.vue
> +        },
Такое описание используется для props. В data используется просто значение.

2018-03-05 08:02 UTC, ocassio commented on src/main/vue/src/components/Auth.vue
> +        errors: []
А зачем тебе это поле?

2018-03-05 08:02 UTC, ocassio commented on src/main/vue/src/components/Auth.vue
> +            api.getCurrentUser()
А почему просто не вызывать метод а-ля /user/authorized, который будет возвращать boolean? Зачем нам сыпать ошибками в консоль, если пользователь не авторизован, и присылать кучу ненужной информации (а зачастую и конфиденциальной), если она нам не нужна?

2018-03-05 08:02 UTC, ocassio commented on src/main/vue/src/components/Auth.vue
> +                .then(this.isAuthorized = true)
И снова, это не функция-обработчик.

2018-03-05 08:02 UTC, ocassio commented on src/main/vue/src/components/NavBar.vue
> +        <Auth/>
Вообще у нас отдельная страница авторизации и кнопка логаута на шторке. Со следующим тикетом уберешь данный компонент.

2018-03-05 08:02 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/config/SecurityConfig.java
>      protected void configure(HttpSecurity http) throws Exception {
Подними конфиг наверх, это основная часть, и она должна быть доступна глазу сразу после открытия файла.

2018-03-06 11:48 UTC, ocassio commented on src/main/vue/src/api/rest/user.api.js
> +        });
Давай все-таки возьмем за правило - получение данных из запроса берет на себя тот, кто вызывает функцию. Здесь просто колл и возвращение промиса. Ну и JSDoc что-то истине не соответствует. 😃

2018-03-06 11:49 UTC, ocassio commented on src/main/vue/src/components/Auth.vue
> +                .then(this.authCheck = false);
1. А почему не одной функцией? Или вообще await, раз ты умеешь им пользоваться.
2. Второй then снова не функцию принимает.

2018-03-06 11:50 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/controllers/UserApiController.java
> +        return restTemplate.getForObject("https://api.github.com/user", String.class);
Замени на возвращение Principal, для начала.

2018-03-06 11:51 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/controllers/UserApiController.java
> +public class UserApiController {
Давай просто UserController. Других все равно не будет.

2018-03-06 11:51 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/config/ReviewSecurityConfig.java
> +    public ReviewSecurityConfig(@Qualifier("oauth2ClientContext") OAuth2ClientContext oauth2ClientContext) {
Добавь Autowired для конструктора.

2018-03-06 11:52 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/config/SecurityConfig.java
> +    }
Давай соблюдать порядок:
1. Константы
2. Поля
3. Конструкторы
4. Методы

2018-03-06 19:05 UTC, ocassio commented
Использование колла isAuthorized неверное. В поле проставляется весь респонс, а не данные. Из-за этого при первом посещении страницы пользователь всегда видит интерфейс таким, будто он залогинен.

![image](https://user-images.githubusercontent.com/6851647/37052485-d710c2b2-2192-11e8-91b6-16e3c8c3b76e.png)

2018-03-06 19:22 UTC, Tadoma commented
Забыл запустить ватчер

2018-03-06 19:23 UTC, ocassio commented on src/main/vue/src/components/Auth.vue
> +        authCheck: Boolean
Еще раз: в data идут сами значения, а не типы. Типы описываются только у пропертей.

2018-03-06 19:28 UTC, ocassio approved these changes

2018-03-06 19:30 UTC, merged