7 features drawer
ncedu-tlt/social-network pull request #13
Opened 2018-03-05 08:17 UTC by ShadowExoriare

2018-03-09 13:17 UTC, ocassio requested changes

2018-03-09 13:17 UTC, ocassio commented on src/main/vue/src/App.vue
> +        <NavBar @OpenDrawer="switchDrawerVisible"/>
1. События именуются в camelCase.
2. Почему NavBar знает о том, что клик по гамбургеру будет использоваться для открытия шторки?

2018-03-09 13:17 UTC, ocassio commented on src/main/vue/src/App.vue
> +        <Drawer :is-drawer-visible-desktop.sync="isDrawerVisibleDesktop" :is-drawer-visible-mobile="isDrawerVisibleMobile"/>
Зачем два параметра?

2018-03-09 13:17 UTC, ocassio commented on src/main/vue/src/App.vue
> +}
Используй брейкпоины Vuetify. И нет смысла выносить это наружу.

2018-03-09 13:17 UTC, ocassio commented on src/main/vue/src/App.vue
> +            isDrawerVisibleMobile: false
В одно поле. Это просто видимость. Родитель не должен разбираться в деталях реализации дочернего элемента.

2018-03-09 13:17 UTC, ocassio commented on src/main/vue/src/components/NavBar.vue
> +            <v-toolbar-side-icon @click.native.stop="uncoverDrawer"/>
А зачем тебе тут модификатор native? Вроде, у иконки есть свой клик.

2018-03-09 13:17 UTC, ocassio commented on src/main/vue/src/i18n/locales/en.js
> +    'drawer.preferences': 'Preferences'
Суть ключей в локалях - в возможности повторного использования. У тебя же они гвоздями прибиты в шторке.

2018-03-09 15:14 UTC, ShadowExoriare commented on src/main/vue/src/App.vue
> +        <Drawer :is-drawer-visible-desktop.sync="isDrawerVisibleDesktop" :is-drawer-visible-mobile="isDrawerVisibleMobile"/>
Один параметр передается для отображения на десктопе, второй для мобилки.

2018-03-09 16:07 UTC, ocassio commented on src/main/vue/src/App.vue
> +        <Drawer :is-drawer-visible-desktop.sync="isDrawerVisibleDesktop" :is-drawer-visible-mobile="isDrawerVisibleMobile"/>
Почему о таких вещах вообще должен App компонент думать? Его задача скрывать или показывать шторку. Как именно это будет происходить - вообще не его ума дела.

2018-03-09 18:48 UTC, ShadowExoriare commented on src/main/vue/src/App.vue
> +        <NavBar @OpenDrawer="switchDrawerVisible"/>
Переименовать событие на "клик по кнопке гамбургера" будет более правильным решением?

2018-03-09 20:24 UTC, ShadowExoriare commented on src/main/vue/src/i18n/locales/en.js
> +    'drawer.preferences': 'Preferences'
Соответственно локализацию не применять к пунктам в шторке?

2018-03-12 20:05 UTC, ocassio requested changes

2018-03-12 20:05 UTC, ocassio commented on src/main/vue/src/App.vue
> +        <NavBar @clickOnHamburgerButton="switchDrawerVisible"/>
Давай сократим до hamburgerClick.

2018-03-12 20:05 UTC, ocassio commented on src/main/vue/src/App.vue
> +        <Drawer :is-drawer-visible.sync="isDrawerVisible"/>
1. Is - это глагол. Глагол - это действие. Действие - это метод. А у нас просто свойство.
2. Мы и так видим, что это шторка. Нет нужды упоминать это еще и в имени параметра.
3. Visible, все-таки, не совсем корректно, так как в минифицированном варианте мы ее все равно видим. Давай лучше opened.

2018-03-12 20:05 UTC, ocassio commented on src/main/vue/src/App.vue
> +            isDrawerVisible: true
Снова is.

2018-03-12 20:05 UTC, ocassio commented on src/main/vue/src/components/Drawer.vue
> +        :permanent="isDrawerVisibleMobileVersion"
Названия сами напрашиваются: minified и visible.

2018-03-12 20:05 UTC, ocassio commented on src/main/vue/src/components/Drawer.vue
> +            required: true
А точно ли он обязателен? Почему бы не сделать его true по дефолту? Тогда шторку можно будет размещать без дополнительного контроля со стороны, и она будет просто отображаться.

2018-03-12 20:05 UTC, ocassio commented on src/main/vue/src/components/Drawer.vue
> +            right: null,
Что за drawer и right?

2018-03-12 20:05 UTC, ocassio commented on src/main/vue/src/components/Drawer.vue
> +            }
1. Когда я говорил, что нужно использовать встроенные брейкпоинты - подразумевалось использование готовых велчин. Ты же оставил хардкод, но получаешь размер окна из нового места. Подразумевалось, что условие будет выглядеть примерно как `this.$vuetify.breakpoint.smAndDown` (в зависимости от того, что именно тебе понадобится).
2. Если я сожму экран - минифицированная версия исчезнет, что правильно. Но если я верну ему прежний размер, то она не появится.

2018-03-12 20:05 UTC, ocassio commented on src/main/vue/src/components/NavBar.vue
> +            <v-toolbar-side-icon @click.stop="uncoverDrawer"/>
1. Почему NabBar снова вспоминает о Drawer? Он же вообще без понятия, с какой целью будет использоваться эта кнопка.
2. На узком экране гамбургер уезжает направо. Сверся с примерами еще разок, возможно ты что-то упустил.

2018-03-12 20:21 UTC, ShadowExoriare commented on src/main/vue/src/App.vue
> +        <NavBar @clickOnHamburgerButton="switchDrawerVisible"/>
Поправил.

2018-03-12 21:14 UTC, ShadowExoriare commented on src/main/vue/src/components/Drawer.vue
> +            required: true
Это гениально!

2018-03-13 10:42 UTC, ShadowExoriare commented on src/main/vue/src/components/Drawer.vue
> +            right: null,
Выпилил, оставались с изначального шаблона.

2018-03-13 10:42 UTC, ShadowExoriare commented on src/main/vue/src/components/Drawer.vue
> +        :permanent="isDrawerVisibleMobileVersion"
minified подсвечивает ошибку, заменил на minify.

2018-03-14 18:53 UTC, ocassio commented
Забыл пункт Log out.

2018-03-15 10:32 UTC, ocassio approved these changes

2018-03-15 10:34 UTC, ocassio requested changes
1. Почему Log out видно только на развернутой версии?
2. А иконки более похожей на выход нет?
3. Log out должен быть прибит к низу шторки.

2018-03-15 17:34 UTC, ocassio approved these changes

2018-03-15 17:35 UTC, merged