Added AuthPage, root dispatcher component, store vuexed
ncedu-tlt/social-network pull request #15
Opened 2018-03-07 20:35 UTC by Tadoma

2018-03-08 10:50 UTC, ocassio requested changes

2018-03-08 10:50 UTC, ocassio commented on src/main/vue/src/components/AuthPage.vue
> +    }
А зачем использовать несколько классов, если все равно навешиваешь одинаковые стили?

2018-03-08 10:50 UTC, ocassio commented on src/main/vue/src/components/AuthPage.vue
> +    }
1. А ты пробовал использовать готовые стили для текста, которые предоставляет Vuetify?
2. Не смотрел, можно ли как нибудь синхронизировать цвет текста с темой?
3. Верстка расползается на мобилке. Поможет правильное использование flex.
<img width="512" alt="default" src="https://screenshotscdn.firefoxusercontent.com/images/e6248fc9-e9a7-4ad6-89a4-7b92cb561ee7.png">

2018-03-08 10:50 UTC, ocassio commented on src/main/vue/src/components/AuthPage.vue
> +        await this.actionAuthCheck();
Используй await только тогда, когда тебе действительно нужно дождаться результата. В данном случае, это нам не нужно.

2018-03-08 10:50 UTC, ocassio commented on src/main/vue/src/components/AuthPage.vue
> +                            @click="logout"
К слову, logout можно также выполнить посредством простого перехода на **/logout**. Но тут на твое усмотрение.

2018-03-08 10:50 UTC, ocassio commented on src/main/vue/src/components/Dispatcher.vue
> +        if (this.authCheck === true) {
Почему не просто `if (this.authCheck)`?

2018-03-08 10:50 UTC, ocassio commented on src/main/vue/src/components/Dispatcher.vue
> +    name: 'Dispatcher',
Подобную логику лучше выполнять в роутере.
Если в кратце, то при попадании на **/** мы должны навигироваться на **/feed**.
Для всех страниц, кроме страницы авторизации должен срабатывать сторожевой хук, который проверяет наличие авторизации в хранилище Vuex. Если авторизация отсутствует, то происходит редирект на страницу авторизации.
Для сохранения состояния между перезагрузками страницы можно использовать флаг в local storage, который будет проставляться после успешной авторизации и убираться про логауте или неудачном запросе.

2018-03-08 10:50 UTC, ocassio commented on src/main/vue/src/i18n/locales/en.js
> +    'auth.login': 'Login through GitHub',
Поправь на Log in via GitHub. Ну и про русскую локаль не забываем.

2018-03-08 10:50 UTC, ocassio commented on src/main/vue/src/router/index.js
>              component: HelloWorld
Эту штуку можно выпилить.

2018-03-08 10:50 UTC, ocassio commented on src/main/vue/src/router/index.js
> +            path: '/welcome',
Я бы все-таки /auth сделал. :)

2018-03-08 10:50 UTC, ocassio commented on src/main/vue/src/store/modules/auth.js
> +    getAuthCheck: state => state.authCheck
Используй геттеры только тогда, когда тебе нужно что-то рассчитать на основе содержимого хранилища. Ну или просто упростить доступ. Ну и не надо их называть так, будто это методы. Для компонентов они выглядят как обычные поля.

2018-03-08 10:50 UTC, ocassio commented on src/main/vue/src/store/modules/auth.js
> +        state.authCheck = authCheckValue;
Лучше setAuth.

2018-03-08 10:50 UTC, ocassio commented on src/main/vue/src/store/modules/auth.js
> +        authCheckValue = response.data;
1. Зачем тебе тут входной параметр? Ты же его даже не используешь.
2. Не надо делать приписку action. Компонентам этого знать не стоит. Просто checkAuth.

2018-03-08 13:35 UTC, ocassio commented on src/main/vue/src/store/modules/auth.js
> +    authCheck: Boolean
Типы указываются ТОЛЬКО для пропертей.

2018-03-12 19:43 UTC, Tadoma commented on src/main/vue/src/components/AuthPage.vue
> +                            @click="logout"
Вроде бы нужен именно POST. По дефолту там 404.

2018-03-12 19:45 UTC, Tadoma commented on src/main/vue/src/components/AuthPage.vue
> +                            @click="logout"
Вроде бы нужен именно POST. По дефолту там 404.

2018-03-12 20:30 UTC, ocassio requested changes

2018-03-12 20:30 UTC, ocassio commented on src/main/vue/src/components/AuthPage.vue
> +export default {name: 'AuthPage',
Это у меня ESLint такое пропускает? Беда, буду править. :)

2018-03-12 20:30 UTC, ocassio commented on src/main/vue/src/components/AuthPage.vue
> +            }
1. Local Storage сейчас все браузеры поддерживают, можно и не оборачивать в условия. Тем более, что у нас логика на это завязана.
2. Простановку параметра лучше делать в самом action'е.
3. Is - глагол. Глагол - действие. Действие - метод. У тебе просто параметр.

2018-03-12 20:30 UTC, ocassio commented on src/main/vue/src/router/index.js
> +    await store.dispatch('auth/checkAuth');
Эм... И пулять запрос перед каждым переключением страницы? Нет, здесь мы опираемся исключительно на значение в state, которое синхронизируется с Local Storage.

2018-03-12 20:30 UTC, ocassio commented on src/main/vue/src/store/modules/auth.js
> +    isAuthed: false
1. Снова is.
2. Значение по умолчанию следует брать из Local Storage. Оно для этого и было сделано.

2018-03-12 20:30 UTC, ocassio commented on src/main/vue/src/store/modules/auth.js
> +        router.push('/');
Vuex не должен управлять роутингом.

2018-03-13 12:50 UTC, Tadoma commented on src/main/vue/src/components/AuthPage.vue
> +export default {name: 'AuthPage',
Я фиксил файл встроенной тулзой, вернуть как было не могу:
Unexpected line break after this opening brace. (object-curly-newline)

2018-03-13 13:18 UTC, Tadoma commented
Есть проблема с роутом после /logout

2018-03-13 17:04 UTC, ocassio commented on src/main/vue/src/components/AuthPage.vue
> +export default {name: 'AuthPage',
А, понял. Нужно еще закрывающую скобку перенести на новую строку. Сейчас у тебя отрабатывает по тому же принципу, чти и такой кейс: `export default { a: 1 }`.

2018-03-14 18:49 UTC, ocassio commented on src/main/vue/src/router/index.js
> +                if (store.state.auth.authed) {
Забыл дождаться выполнения.

2018-03-14 19:35 UTC, ocassio approved these changes

2018-03-14 19:36 UTC, merged