Added rest api call for getting project list of user, also added component...
ncedu-tlt/social-network pull request #22
Opened 2018-03-21 09:43 UTC by Tadoma

Closes #16

2018-03-21 09:58 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/controllers/UserController.java
> +    @RequestMapping("/api/user/{userName}/repos")
Вынеси `/api/user` на уровень класса. Иначе устанете переписывать. :)

2018-03-21 10:09 UTC, ocassio requested changes
И подтяни изменения из мастера. Там должна быть шторка, сразу добавь там переход на твою страницу при клике на Projects.

В целом - здорово. :)

2018-03-21 10:09 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/controllers/UserController.java
> +        return restTemplate.getForObject("https://api.github.com/users/" + userName + "/repos", Project[].class);
1. По поводу комментария - я за.
2. Давай инкапсулируем все запросы к GitHub API в отдельном сервисном слое. Я там где-то создавал пакет api, создай в нем пакеты modules и services с соответствующим наполнением. Модельки пусть содержат какой-нибудь постфикс в стиле GitHubModel (если придумаешь покороче, я буду только рад).
3. Адреса API endpoint'ов вынеси в отдельный класс с константами, которые будут конструироваться по такому же принципу, как мы делали в simple-web для JSP. В адресах будут плейсхолдеры, как ты предложил.
4. Списки лучше возвращать в виде List, оно поуниверсальней.

2018-03-21 10:09 UTC, ocassio commented on src/main/vue/src/components/ProjectList.vue
> +        // delayed
Лучше mounted. При переиспользовании проблем меньше будет.

2018-03-21 10:09 UTC, ocassio commented on src/main/vue/src/components/ProjectList.vue
> +            default: 'ocassio',
Верное замечание, отдаем на откуп родителю.
Делаем `required: true ` и создаем компонент ProjectsPage. В нем будет более точное позиционирование (на отдельной странице можно сделать болеее четкое центрирование) и маппинг на Vuex с текущим пользователем, который проставляется туда в момент проверки авторизации.

2018-03-28 10:12 UTC, ocassio requested changes

2018-03-28 10:12 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/consts/GhubApiAddr.java
> +public class GhubApiAddr {
Ну ты уж не борщи с сокращениями. :) GitHubEndpoints вполне сойдет. И перемести в пакет api, все-таки это специфичная вещь. Зато у параметров можно убрать URL, там как там ничего больше и не будет, а из названия класса уже все ясно.

2018-03-28 10:12 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/api/services/UserController.java
> +        return restTemplate.getForObject(sub.replace("${USERS_URL}" + userName + "/repos"), List.class);
Чтобы ты оценил масштаб трагедии.
Вместо того, чтобы просто воспользоваться константой GhubApiAddr.USERS_URL, ты:
1. Заюзал рефлексию. Если у тебя в принципе возникает идея использовать рефлексию стоит сильно задуматься, так как это ломает все, что продвигает Java. Как правило, она используется только в исключительных случаях опытными разработчиками.
2. Заюзал стороннюю библиотеку.
3. Инстанцировал два объкта.
4. Написал строку "${USERS_URL}", которая не поддается анализу со стороны IDE.
5. Запустил парсинг и модификацию строки.

---------------------------

Теперь давай напишу, что возникало у меня в голове, когда мы обсуждали эту тему.
1. Класс GitHubEndpoints содержит константы с адресами.
2. Там встречаются адреса вида:
   ```java
   public static final String USER_REPOS = BASE + "/users/${userId}/repos";
   ```
3. Сервис, который хочет постучаться на данный endpoint, собирает мапу с параметрами и выполняет подмену в строке а-ля:
   ```java
   StringSubstitutor.replace(GitHubEndpoints.USER_REPOS, params)
   ```
4. По полученному адресу совершается запрос.

2018-03-28 10:12 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/api/models/ProjectGhubMod.java
> +public class ProjectGhubMod {
Mod - не очевидно. Давай GitHubDTO.

2018-03-28 10:12 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/api/services/UserController.java
> +package ru.ncedu.socialnetwork.api.services;
Контроллер должен остаться в контроллерах.
Тебе нужно было именно создать отдельный сервис, который бы просто ходил на GitHub с заданными параметрами и возвращал результат.

2018-03-28 11:10 UTC, ocassio requested changes

2018-03-28 11:10 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/api/services/UserController.java
> +        });
Зачем нам весь этот огород? Почему просто не вернуть пользователя даже если там null? А на клиенте уже посмотреть, что пришло.

2018-03-28 11:10 UTC, ocassio commented on src/main/vue/src/store/modules/auth.js
> +    authed: localStorage.getItem('authed')
Замени тогда атрибут на userName. Я ведб правильно понял, что ты именно его там хранишь?

2018-03-28 11:10 UTC, ocassio commented on src/main/vue/src/store/modules/auth.js
>          }
А если не прошел проверку? Вычищать данные не будем?

2018-03-28 11:38 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/api/services/UserController.java
> +    @RequestMapping("/authorized")
И еще у тебя уже есть getUser, который идеально подходит для данной задачи.

2018-03-29 08:46 UTC, ocassio requested changes

2018-03-29 08:46 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/api/models/ProjectVO.java
> +public class ProjectVO implements Serializable {
А что значит VO? И нам разве нужен Serializable?

2018-03-29 08:46 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/api/services/GitHubService.java
> +public class GitHubService {
Мы все в одном сервисе не уместим. :)
Делаем также, по тематикам: пользователи, проекты и т.п.
Можно прям по секциям в документации GitHub API.

2018-03-29 08:46 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/api/services/GitHubService.java
> +    private Map params;
А зачем мы шарим мапу? Знаешь какое веселье начнется, когда к тебе зайдут несколько пользователей?)

2018-03-29 14:47 UTC, Tadoma commented on src/main/java/ru/ncedu/socialnetwork/api/models/ProjectVO.java
> +public class ProjectVO implements Serializable {
>>Value object 
Usually used for data transfer between the business layer

Пытался применить naming conventions, видел в примерах

2018-03-29 18:44 UTC, ocassio approved these changes

2018-03-29 18:44 UTC, merged