11 profile info
ncedu-tlt/social-network pull request #25
Opened 2018-03-30 17:56 UTC by IngerGodal

2018-05-07 08:48 UTC, ocassio commented
Сборка упала.

2018-05-10 14:17 UTC, ocassio requested changes

2018-05-10 14:17 UTC, ocassio commented on src/main/vue/package.json
> +    "npm": "^6.0.0",
Как вы все умудряетесь npm в зависимости запихнуть?) Убираем.

2018-05-10 14:17 UTC, ocassio commented on src/main/vue/src/components/ProfileInfo.vue
> +                <p class="body-1 primary--text darken-0">{{ profile.job }}</p>
Сделай тоже списком, чтобы оформление так не выделялось.

2018-05-10 14:17 UTC, ocassio commented on src/main/vue/src/components/ProfileInfo.vue
> +                <p class="body-1 primary--text darken-0">{{ profile.placeOfWork }}</p>
Сделай тоже списком, чтобы оформление так не выделялось.

2018-05-30 16:44 UTC, ocassio requested changes
Все отлично. Убирай обозначенные изменения и будем мержиться.

2018-05-30 16:44 UTC, ocassio commented on src/main/vue/config/index.js
> +                proxyOptions,
А сюда то ты зачем залезла? :)

2018-05-30 16:44 UTC, ocassio commented on src/main/vue/package.json
> +    "npm": "^6.0.0",
До сих пор актуально.

2018-05-30 18:33 UTC, IngerGodal commented on src/main/vue/config/index.js
> +                proxyOptions,
idea на это ругалась (:

2018-05-30 19:16 UTC, ocassio approved these changes

2018-05-30 19:17 UTC, merged