37-ChatList
ncedu-tlt/social-network pull request #38
Opened 2018-04-21 11:56 UTC by Tadoma

Closes #37

2018-04-22 10:52 UTC, ocassio requested changes

2018-04-22 10:52 UTC, ocassio commented on src/main/vue/src/components/ChatList.vue
> +                style="max-height: 450px"
Тут нужно отталкиваться именно от размера экрана.
450px неэффективно используют доступное пространство на десктопах, но могут выйти за пределы экрана на устройствах поменьше.

2018-04-22 10:52 UTC, ocassio commented on src/main/vue/src/components/ChatList.vue
> +                    <v-list-tile avatar :key="key" @click="$router.push(`/chat/${chat.id}`)">
В качестве ключа лучше использовать chat.id.

2018-04-22 10:52 UTC, ocassio commented on src/main/vue/src/components/ChatList.vue
> +                        <v-list-tile-action-text>{{ chat.dateMsg }}</v-list-tile-action-text>
У нас форматирование будет происходить на сервере? Если да, то ок. Если нет, можно использовать те же механизмы, что использовал Ваня в ленте.

2018-04-22 10:52 UTC, ocassio commented on src/main/vue/src/components/AddChat.vue
> +            <v-card-title>Select friends</v-card-title>
Забыл про локализацию, относится ко всем текстовкам.

2018-04-22 10:52 UTC, ocassio commented on src/main/vue/src/components/AddChat.vue
> +                    <v-list :key="index">
Лучше использовать идентификатор пользователя. Использование индекса, особенно вкупе с фильтрацией, в лучшем случае - не оптимально, в худшем может привести к отрисовке неверных элементов.

2018-04-22 10:52 UTC, ocassio commented on src/main/vue/src/components/AddChat.vue
> +            <v-card-text style="height: 300px;">
1. Inline-стили не используем.
2. Избегаем жестко заданных высот. Хотя бы замени на max-height.

2018-04-22 10:52 UTC, ocassio commented on src/main/vue/src/components/AddChat.vue
> +                                <v-list-tile-sub-title v-html="friend.status"/>
Для статуса нужна локализация.

2018-04-22 10:52 UTC, ocassio commented on src/main/vue/src/components/AddChat.vue
> +                this.exist = this.getChatByLogin(this.selectedLogin.toString()).length === 1;
А почему именно логин, а не id? В принципе, он уникален, но все же интересно)

2018-04-22 12:03 UTC, Tadoma commented on src/main/vue/src/components/ChatList.vue
> +                    <v-list-tile avatar :key="key" @click="$router.push(`/chat/${chat.id}`)">
Тогда будет конфликт с ключами v-divider

2018-04-22 13:16 UTC, Tadoma commented on src/main/vue/src/components/AddChat.vue
> +                this.exist = this.getChatByLogin(this.selectedLogin.toString()).length === 1;
Я как-то сразу в сторе chat.participants с логинами написал, более наглядно что ли. А что быстрее: сравнение string или int?

2018-04-22 14:35 UTC, ocassio commented on src/main/vue/src/components/ChatList.vue
> +                    <v-list-tile avatar :key="key" @click="$router.push(`/chat/${chat.id}`)">
Смотри, divider у тебя же всегда одинаковый?
Следовательно, можно либо вообще не задавать для него ключ, либо задать, но один статичный (в таком случае Vue будет всегда использовать один и тот же divider для всех элементов списка, что должно даже ускорить скорость работы).
Чтобы приглушить ESLint, поставь на строке, предшествующей v-divider такой комментарий: `<!-- eslint-disable-next-line vue/valid-v-for -->`

2018-04-22 14:37 UTC, ocassio commented on src/main/vue/src/components/AddChat.vue
> +                this.exist = this.getChatByLogin(this.selectedLogin.toString()).length === 1;
Если не займет много времени, то давай. Это действительно незначительно ускорит скорость работы и уменьшит объем передаваемых данных, но в нашем случае это некритично.

2018-04-22 17:27 UTC, ocassio commented on src/main/vue/src/components/ChatList.vue
> +        max-height: 60vh
Хотелось бы все-таки увидеть использование доступного пространства по максимуму.
Посмотри, как это нарисовано в мокапах.

2018-04-22 19:43 UTC, ocassio commented on src/main/vue/src/components/ChatList.vue
> +        max-height: 72vh;
Ты пытаешься подобрать высоту, а нужно просто использовать все доступное пространство.

2018-04-25 07:51 UTC, ocassio commented
## Декстоп
![](https://image.ibb.co/iYXzRx/screenshot_ncedu_social_network_pr_38_herokuapp_com_2018_04_25_11_25_32.png)

### Проблемы

1. Отступ снизу отсутствует
2. Отступ справа != отступу слева

## Мобилка

![https://image.ibb.co/cNOTKH/ncedu_social_network_pr_38_herokuapp_com_i_Phone_5_SE.png](https://image.ibb.co/cNOTKH/ncedu_social_network_pr_38_herokuapp_com_i_Phone_5_SE.png)

### Проблемы

1. Экран уезжает за правую грань
2. Также отсутвует отступ снизу

2018-04-25 13:51 UTC, ocassio approved these changes

2018-04-25 13:52 UTC, merged