Drawer implement's
ncedu-tlt/social-network pull request #46
Opened 2018-05-12 10:00 UTC by ShadowExoriare

2018-05-12 10:13 UTC, ocassio requested changes

2018-05-12 10:13 UTC, ocassio commented on src/main/vue/src/components/Drawer.vue
> +                avatar: this.$store.state.auth.userAvatar ? this.$store.state.auth.userAvatar : 'https://randomuser.me/api/portraits/men/85.jpg'
Может в качестве дефолтной опции что-нибудь более абстрактное? :)

2018-05-12 10:13 UTC, ocassio commented on src/main/vue/src/components/Drawer.vue
> +                        <v-list-tile-sub-title>dev</v-list-tile-sub-title>
А где должность потерял? И давай лучше все-таки организацию выводить.

2018-05-12 10:13 UTC, ocassio commented on src/main/vue/src/components/Drawer.vue
> +                realName: this.$store.state.auth.userRealName ? this.$store.state.auth.userRealName : 'Unnamed Person',
У нас, вроде как, не может быть пользователя без имени. Даже, если на GitHub ничего не указано, будет использоваться его логин.

2018-05-13 14:18 UTC, ocassio commented
Организация не отображается.

2018-05-14 12:28 UTC, ocassio commented
1. Зачем ты опять разделил логику для мобилок и десктопа?
2. Шторка для мобилки теперь отображается в минимизированном варианте.

2018-05-14 17:21 UTC, ocassio requested changes

2018-05-14 17:21 UTC, ocassio commented on src/main/vue/src/components/Drawer.vue
> +                this.$emit('update:disableVisible');
А зачем создавать новый ивент, если у тебя уже есть visible пропертя?

2018-05-14 19:51 UTC, ShadowExoriare commented on src/main/vue/src/components/Drawer.vue
> +                this.$emit('update:disableVisible');
Не дает изменять пропертю сходу, я пытался, только с эмитом к родителю.

2018-05-14 20:12 UTC, ocassio commented on src/main/vue/src/components/Drawer.vue
> +                this.$emit('update:disableVisible');
Потому что нужно заэмитить событие обновления проперти.

2018-05-17 11:52 UTC, ocassio approved these changes

2018-05-17 11:53 UTC, merged