45 chatlist server logic
ncedu-tlt/social-network pull request #52
Opened 2018-05-30 21:01 UTC by Tadoma

2018-05-31 08:48 UTC, ocassio requested changes

2018-05-31 08:48 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/domain/ChatDAO.java
> +    private String name;
Уникальность имени, кстати, спорный момент.
Создаст один человек чат "Универ" и больше никто не сможет.

2018-05-31 08:48 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/domain/ChatDAO.java
> +    private Date dateMsg;
А это дата чего?

2018-05-31 08:48 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/domain/ChatDAO.java
> +    private Collection<Integer> participantsId;
Тут полноценная связь нужна.

2018-05-31 08:48 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/domain/MessageDAO.java
> +    private int fromId;
Тоже нужна полноценная свзяь.

2018-05-31 08:48 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/repositories/ChatRepository.java
> +    ChatDAO findById(int id);
Такой метод вроде должен быть по дефолту.

2018-05-31 08:48 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/repositories/UserRepository.java
> +    UserDAO findByUserId(int id);
Должен быть по умолчанию.

2018-05-31 08:48 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/services/ChatService.java
> +        return chatRepository.findByParticipantsId(id);
Такие вещи можно еще разруливать добавление полем chats на самом юзере. Заодно будет свзяь между таблицами и каскадное удаление.

2018-05-31 08:48 UTC, ocassio commented on src/main/vue/src/api/rest/chat.api.js
> +    return client.get(`/chat`);
Используй ` только если тебе реально нужны возможности шаблонных строк. Иначе браузер только лишние действия совершает.

2018-05-31 17:23 UTC, ocassio requested changes

2018-05-31 17:23 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/domain/ChatDAO.java
> +    private Collection<ParticipantId> participantsId = new ArrayList<>();
А зачем нам отдельная сущность ParticipantId? Почему нельзя сразу юзеров использовать?

2018-05-31 17:23 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/domain/ChatDAO.java
> +    private Collection<MessageDAO> messages = new ArrayList<>();
Тут еще нужно отдельный action на удаление прописывать, чтобы каскадка заработала. Посмотри, как это у Дениса было сделано.

2018-05-31 17:23 UTC, ocassio commented on src/main/vue/src/store/modules/chats.js
>              id: state.chats.length + 1,
А почему идентификатор генерируется на фронтенде? Это вообще задача самой базы данных.

2018-05-31 17:23 UTC, ocassio commented on src/main/vue/src/store/modules/chats.js
>              participantsId: people.map(p => p.id)
Слишком много данных формируется на фронтенде. По сути, единственное, что нужно бэку - список пользователей.

2018-05-31 17:23 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/services/ChatService.java
> +    public List<ChatDAO> getChats(@AuthenticationPrincipal UserDAO user) {
Зачем тут аннотация? Ты же всегда явно передаешь параметр и никакой DI тут не задействован.

2018-05-31 17:23 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/services/ChatService.java
> +        return chatRepository.save(chat);
Вот тут бы хотелось увидеть защиту от создания чата с пользователем, с которым уже есть переписка.

2018-05-31 17:23 UTC, ocassio commented on src/main/java/ru/ncedu/socialnetwork/domain/MessageDAO.java
> +    private FromId fromId;
Embdedded используется для составных ключей. В данном случае:
1. Это не ключ.
2. Внутри одно поле.

И вообще, тут явно напрашивается связь с пользователем.

2018-06-01 09:04 UTC, Tadoma commented
Есть проблема с хранением поля participantsId чата, на бэке связь ManyToMany через чат и юзера.

2018-06-17 17:50 UTC, ocassio approved these changes

2018-06-17 17:50 UTC, merged