Added NavBar, hamburger menu applied mockup color.
ncedu-tlt/social-network pull request #6
Opened 2018-02-26 20:11 UTC by ShadowExoriare

2018-02-27 07:40 UTC, ocassio requested changes

2018-02-27 07:40 UTC, ocassio commented on src/main/vue/src/App.vue
> +        <nav-bar>Nav-bar</nav-bar>
1. Зачем в тело тега записывать Nav-bar? Оно же игнорируется.
2. Для наших компонентов используем UpperCamelCase.

2018-02-27 07:40 UTC, ocassio commented on src/main/vue/src/App.vue
> -    name: 'App'
Имена для компонентов проставляем в обязательном порядке. А ты еще и старое удалил.

2018-02-27 07:40 UTC, ocassio commented on src/main/vue/src/App.vue
> +        <v-content class="form-content">
Не используем кастомные классы без крайней необходимости.

2018-02-27 07:40 UTC, ocassio commented on src/main/vue/src/App.vue
> +.form-content {
Если тебе просто мешали старые стили, стоило их удалить. Это просто заглушка.

2018-02-27 07:40 UTC, ocassio commented on src/main/vue/src/components/NavBar.vue
> +    <v-toolbar dark color="purple darken-3" fixed app>
Используй тему вместо явных цветов.

2018-02-27 07:40 UTC, ocassio commented on src/main/vue/src/components/NavBar.vue
> +        <v-toolbar-side-icon></v-toolbar-side-icon>
ESLint не настроил. Иначе, тебе бы IDEA выдала ошибку.
Подтяни изменения из мастера, я добавил более явные ESLint проверки.
Используй npm run server при разработке UI. Помимо прочего, он умеет выдавать ошибки ESLint.

2018-02-27 07:40 UTC, ocassio commented on src/main/vue/src/components/NavBar.vue
> +<script>
1. Если тебе не нужна какая-либо секция - не пиши ее.
2. Нужно явно указать имя компонента.

2018-02-27 07:40 UTC, ocassio commented on src/main/vue/src/components/NavBar.vue
> +    .form-avatar{
Зачем тут этот стиль?

2018-02-27 14:18 UTC, ShadowExoriare commented on src/main/vue/src/App.vue
> +        <nav-bar>Nav-bar</nav-bar>
Поправил.

2018-02-27 14:18 UTC, ShadowExoriare commented on src/main/vue/src/App.vue
> -    name: 'App'
Добавил имя.

2018-02-27 14:19 UTC, ShadowExoriare commented on src/main/vue/src/App.vue
> +        <v-content class="form-content">
Убрал стили для контента.

2018-02-27 14:19 UTC, ShadowExoriare commented on src/main/vue/src/App.vue
> +.form-content {
Убрал стили для контента.

2018-02-27 14:19 UTC, ShadowExoriare commented on src/main/vue/src/components/NavBar.vue
> +    <v-toolbar dark color="purple darken-3" fixed app>
Заюзал primary color, импортнул описание цветов в конфиг.

2018-02-27 14:20 UTC, ShadowExoriare commented on src/main/vue/src/components/NavBar.vue
> +        <v-toolbar-side-icon></v-toolbar-side-icon>
Настроен. npm юзал на старте.

2018-02-27 14:21 UTC, ShadowExoriare commented on src/main/vue/src/components/NavBar.vue
> +    .form-avatar{
Выпилил стиль, аватарку.

2018-02-27 14:22 UTC, ShadowExoriare commented on src/main/vue/src/components/NavBar.vue
> +<script>
Проверил секции, оставил только те, которые используются.

2018-02-27 14:27 UTC, ocassio commented on src/main/vue/src/components/NavBar.vue
> +<script>
Да ну?) А пустой script и style прям вовсю эксплуатируются?)
И имени компонента я так и не увидел.

2018-02-27 14:34 UTC, ocassio commented
И подмержить мастер не забудь. Теперь ветки с рассинхроном в принципе не пропускаем.

2018-02-27 18:08 UTC, ShadowExoriare commented on src/main/vue/src/components/NavBar.vue
> +<script>
Мастер подмержил, добавил имя элементу, убрал стили.

2018-02-27 18:14 UTC, ocassio commented on src/main/vue/src/App.vue
>  </style>
Еще один блок забыл :)

2018-02-27 19:23 UTC, ShadowExoriare commented on src/main/vue/src/App.vue
>  </style>
Хм... не думал что главный файл приложения может собраться без блоков. Убрал.

2018-02-28 05:49 UTC, ocassio approved these changes

2018-02-28 05:50 UTC, merged